const mongoose = require('mongoose')
const User = require('../models/User')
const Building = require('../models/Building')
const Room = require('../models/Room')
const Booking = require('../models/Booking')
const Approver = require('../models/Approver')
const { ROLE } = require('../constant.js')
const { INSTITUTION } = require('../constant.js')
const Institution = require('../models/Institution')
mongoose.connect('mongodb://localhost:27017/project')
async function clearUser () {
  await User.deleteMany({})
  await Building.deleteMany({})
  await Room.deleteMany({})
  await Institution.deleteMany({})
  await Booking.deleteMany({})
  await Approver.deleteMany({})
}
async function main () {
  await clearUser()
  // for (let i = 1; i < 12; i++) {
  const InstitutionIF = new Institution({ name: INSTITUTION.IF })
  const user1 = new User({ username: 'phai@mail.com', password: 'password', name: 'Naphat', surname: 'Tisonthi', roles: [ROLE.USER], institution: InstitutionIF })
  const user2 = new User({ username: 'book@mail.com', password: 'password', name: 'Jirat', surname: 'Klomkleaw', roles: [ROLE.USER], institution: InstitutionIF })
  const user3 = new User({ username: 'sumo@mail.com', password: 'password', name: 'Chenpob', surname: 'Nopakiat', roles: [ROLE.USER], institution: InstitutionIF })
  const admin1 = new User({ username: 'admin1@mail.com', password: 'password', name: 'Worawit', surname: 'Werapan', roles: [ROLE.ADMIN], institution: InstitutionIF })
  const approver1 = new User({ username: 'approver1@mail.com', password: 'password', name: 'Pichet', surname: 'Wayalun', roles: [ROLE.APPROVER], institution: InstitutionIF })
  const approver2 = new User({ username: 'approver2@mail.com', password: 'password', name: 'Tidarat', surname: 'Pawapattarakul', roles: [ROLE.APPROVER], institution: InstitutionIF })

  const BuildingIF = new Building({ code: 'IF', name: 'อาคารคณะวิทยาการสารสนเทศ', floor: 11, institution: InstitutionIF })
  const room212 = new Room({ code: 'IF', name: '212', equipment: 'Computer+Projector+OHP', capacity: 30, floor: 2, building: BuildingIF, approveres: [approver1, approver2] })
  const room3C01 = new Room({ code: 'IF', name: '3C01', equipment: 'Computer+Projector+OHP', capacity: 60, floor: 3, building: BuildingIF, approveres: [approver1, approver2] })
  const room3C02 = new Room({ code: 'IF', name: '3C02', equipment: 'Computer+Projector+OHP', capacity: 60, floor: 3, building: BuildingIF, approveres: [approver1, approver2] })
  const room3C03 = new Room({ code: 'IF', name: '3C03', equipment: 'Computer+Projector+OHP', capacity: 60, floor: 3, building: BuildingIF, approveres: [approver1, approver2] })
  const room3C04 = new Room({ code: 'IF', name: '3C04', equipment: 'Computer+Projector+OHP', capacity: 60, floor: 3, building: BuildingIF, approveres: [approver1, approver2] })
  const room5M210 = new Room({ code: 'IF', name: '5M210', equipment: 'Projector+OHP ', capacity: 210, floor: 5, building: BuildingIF, approveres: [approver1, approver2] })
  const room11M280 = new Room({ code: 'IF', name: '11M280', equipment: 'Projector+OHP', capacity: 280, floor: 11, building: BuildingIF, approveres: [approver1, approver2] })
  const event1 = new Booking({ transactionDate: new Date('2022-04-09 06:30'), startDate: new Date('2022-04-09 08:00'), endDate: new Date('2022-04-09 16:00'), reason: 'ประชุมการเรียนการสอน', tool: 'Computer+Projector+OHP', room: room3C01, user: user1 })
  const event2 = new Booking({ transactionDate: new Date('2022-04-12 06:30'), startDate: new Date('2022-04-19 09:00'), endDate: new Date('2022-04-19 10:00'), reason: 'Presentงานอาจารย์กบ', tool: 'Computer+Projector+OHP', room: room11M280, user: user2 })
  const Approver1 = new Approver({ user: approver1 })
  const Approver2 = new Approver({ user: approver2 })

  user1.save()
  user2.save()
  user3.save()
  admin1.save()
  approver1.save()
  approver2.save()
  Approver1.save()
  Approver2.save()
  InstitutionIF.users.push(user1)
  InstitutionIF.users.push(user2)
  InstitutionIF.users.push(user3)
  InstitutionIF.users.push(admin1)
  InstitutionIF.users.push(approver1)
  InstitutionIF.users.push(approver2)
  BuildingIF.rooms.push(room212)
  BuildingIF.rooms.push(room3C01)
  BuildingIF.rooms.push(room3C02)
  BuildingIF.rooms.push(room3C03)
  BuildingIF.rooms.push(room3C04)
  BuildingIF.rooms.push(room5M210)
  BuildingIF.rooms.push(room11M280)
  event1.approveres.push(Approver1)
  event1.approveres.push(Approver2)
  event2.approveres.push(Approver1)
  event2.approveres.push(Approver2)
  InstitutionIF.save()
  BuildingIF.save()
  await event1.save()
  await event2.save()
  await room212.save()
  await room3C01.save()
  await room3C02.save()
  await room3C03.save()
  await room3C04.save()
  await room5M210.save()
  await room11M280.save()

  // BuildingMs
  const InstitutionMS = new Institution({ name: INSTITUTION.MS })
  const user4 = new User({ username: 'son@mail.com', password: 'password', name: 'Yannapon', surname: 'Surak', roles: [ROLE.USER], institution: InstitutionMS })
  const user5 = new User({ username: 'benten@mail.com', password: 'password', name: 'Puchong', surname: 'Sumalanukun', roles: [ROLE.USER], institution: InstitutionMS })
  const admin2 = new User({ username: 'admin2@mail.com', password: 'password', name: 'Jakkarin', surname: 'Suksawaschon', roles: [ROLE.ADMIN], institution: InstitutionMS })
  const approver3 = new User({ username: 'approver3@mail.com', password: 'password', name: 'Kanokwan', surname: 'Sarojna', roles: [ROLE.APPROVER], institution: InstitutionMS })
  const approver4 = new User({ username: 'approver4@mail.com', password: 'password', name: 'Jettarin', surname: 'Kapuekngam', roles: [ROLE.APPROVER], institution: InstitutionMS })

  const BuildingMS = new Building({ code: 'MS', name: 'อาคารวิทยาศาสตร์การแพทย์', floor: 6, institution: InstitutionMS })
  const room103 = new Room({ code: 'MS', name: '103', equipment: 'Presenter+TV+OHP+Tape', capacity: 60, floor: 1, building: BuildingMS, approveres: [approver3, approver4] })
  const room107 = new Room({ code: 'MS', name: '107', equipment: 'Presenter+TV+OHP+Tape', capacity: 32, floor: 1, building: BuildingMS, approveres: [approver3, approver4] })
  const room202 = new Room({ code: 'MS', name: '202', equipment: 'Presenter+TV+OHP+Tape', capacity: 98, floor: 2, building: BuildingMS, approveres: [approver3, approver4] })
  const room203 = new Room({ code: 'MS', name: '203', equipment: 'Presenter+TV+OHP+Tape', capacity: 80, floor: 2, building: BuildingMS, approveres: [approver3, approver4] })
  const room603 = new Room({ code: 'MS', name: '603', equipment: 'Lab', capacity: 40, floor: 6, building: BuildingMS, approveres: [approver3, approver4] })
  const event3 = new Booking({ transactionDate: new Date('2022-04-11 08:30'), startDate: new Date('2022-04-12 15:00'), endDate: new Date('2022-04-12 20:00'), reason: 'ติวหนังสือก่อนสอบ', tool: 'Presenter+TV+OHP+Tape', room: room107, user: user1 })
  const Approver3 = new Approver({ user: approver3 })
  const Approver4 = new Approver({ user: approver4 })

  user4.save()
  user5.save()
  admin2.save()
  approver3.save()
  approver4.save()
  Approver3.save()
  Approver4.save()
  InstitutionMS.save()
  InstitutionMS.users.push(user4)
  InstitutionMS.users.push(user5)
  InstitutionMS.users.push(admin2)
  InstitutionMS.users.push(approver3)
  InstitutionMS.users.push(approver4)
  BuildingMS.rooms.push(room103)
  BuildingMS.rooms.push(room107)
  BuildingMS.rooms.push(room202)
  BuildingMS.rooms.push(room103)
  BuildingMS.rooms.push(room603)
  event3.approveres.push(Approver3)
  event3.approveres.push(Approver4)
  BuildingMS.save()
  await event3.save()
  await room103.save()
  await room107.save()
  await room202.save()
  await room203.save()
  await room603.save()

  // }
}

main().then(function () {
  console.log('Finish')
})
