const mongoose = require('mongoose')
const User = require('../models/User')
const Building = require('../models/Building')
const Room = require('../models/Room')
const Booking = require('../models/Booking')
const { ROLE } = require('../constant.js')
const { INSTITUTION } = require('../constant.js')
const Institution = require('../models/Institution')
mongoose.connect('mongodb://localhost:27017/project')
async function clearUser () {
  await User.deleteMany({})
  await Building.deleteMany({})
  await Room.deleteMany({})
  await Institution.deleteMany({})
  await Booking.deleteMany({})
}
async function main () {
  await clearUser()
  // for (let i = 1; i < 12; i++) {
  const InstitutionIF = new Institution({ name: INSTITUTION.IF })
  const InstitutionBS = new Institution({ name: INSTITUTION.BS })
  const user = new User({ username: 'user@mail.com', password: 'password', name: 'Naphat', surname: 'Tisonthi', roles: [ROLE.USER], institution: InstitutionIF })
  const approver = new User({ username: 'approver@mail.com', password: 'password', name: 'Jirat', surname: 'Klomkleaw', roles: [ROLE.APPROVER, ROLE.USER], institution: InstitutionIF })
  const approver2 = new User({ username: 'approver2@mail.com', password: 'password', name: 'Puchong', surname: 'Sumalanukun', roles: [ROLE.APPROVER, ROLE.USER], institution: InstitutionIF })
  const admin = new User({ username: 'admin@mail.com', password: 'password', name: 'Yannapon', surname: 'Surak', roles: [ROLE.ADMIN, ROLE.USER], institution: InstitutionIF })
  const localAdmin = new User({ username: 'local_admin@mail.com', password: 'password', name: 'Chenpob', surname: 'Nopakiat', roles: [ROLE.LOCAL_ADMIN, ROLE.ADMIN, ROLE.USER], institution: InstitutionIF })

  const ApproveUser = new User({ username: 'approver@mail.com', password: 'password', name: 'Jirat', surname: 'Klomkleaw', roles: [ROLE.APPROVER, ROLE.USER], institution: InstitutionIF })
  const BuildingIF = new Building({ code: 'IF', name: 'Informatics', floor: 11, institution: InstitutionIF })
  const UserIF = new User({ username: 'user@mail.com', password: 'password', name: 'Naphat', surname: 'Tisonthi', roles: [ROLE.USER], institution: InstitutionIF })
  const room3C01 = new Room({ name: '3C01', capacity: 200, floor: 3, building: BuildingIF, approveres: ApproveUser })
  const room4C01 = new Room({ name: '4c01', capacity: 150, floor: 4, building: BuildingIF, approveres: ApproveUser })
  const room5C01 = new Room({ name: '5c01', capacity: 100, floor: 5, building: BuildingIF, approveres: ApproveUser })
  const event1 = new Booking({ transactionDate: new Date('2022-04-09 06:30'), startDate: new Date('2022-04-09 08:00'), endDate: new Date('2022-04-09 16:00'), reason: 'ประชุมการเรียนการสอน', tool: 'โปรเจคเตอร์, ไมค์, ลำโพง', room: room3C01, user: UserIF, approveres: ApproveUser })

  user.save()
  approver.save()
  approver2.save()
  admin.save()
  localAdmin.save()
  InstitutionIF.users.push(user)
  InstitutionIF.users.push(approver)
  InstitutionIF.users.push(approver2)
  InstitutionIF.users.push(admin)
  InstitutionIF.users.push(localAdmin)
  BuildingIF.rooms.push(room3C01)
  BuildingIF.rooms.push(room4C01)
  BuildingIF.rooms.push(room5C01)
  InstitutionIF.save()
  InstitutionBS.save()
  BuildingIF.save()
  ApproveUser.save()
  UserIF.save()
  await event1.save()
  await room3C01.save()
  await room4C01.save()
  await room5C01.save()

  // }
}

main().then(function () {
  console.log('Finish')
})
