const express = require('express')
const cors = require('cors')
const path = require('path')
const cookieParser = require('cookie-parser')
const logger = require('morgan')
const mongoose = require('mongoose')
const dotenv = require('dotenv')
dotenv.config()
mongoose.connect('mongodb://localhost:27017/project')

const indexRouter = require('./routes/index')
const usersRouter = require('./routes/user')
const authRouter = require('./routes/auth')
const buildingRouter = require('./routes/building')
const roomRouter = require('./routes/room')
const bookingRouter = require('./routes/booking')
// const { authenMiddleware, authorizeMiddleware } = require('./helpers/auth')
// const { ROLE } = require('./constant')

const app = express()
app.use(logger('dev'))
app.use(cors())
app.use(express.json())
app.use(express.urlencoded({ extended: true }))
app.use(cookieParser())
app.use(express.static(path.join(__dirname, 'public')))

app.use('/', indexRouter)
// app.use('/users', authenMiddleware, authorizeMiddleware([ROLE.ADMIN, ROLE.LOCAL_ADMIN]), usersRouter)
app.use('/users', usersRouter)
app.use('/building', buildingRouter)
app.use('/room', roomRouter)
app.use('/booking', bookingRouter)
app.use('/auth', authRouter)

module.exports = app
